global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: windows-host
    static_configs:
      - targets:
        - host.docker.internal:9182

  - job_name: python_app
    static_configs:
      - targets:
          - python_app:8000

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
        - pushgateway:9091
