version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prom_data:/prometheus"
      - "$PWD/prom_config:/etc/prometheus"
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "$PWD/alert_data:/data"
      - "$PWD/alert_config:/config"
    command: --config.file=/config/alertmanager.yml --log.level=debug